@api = http://localhost:3000/api/v1/


GET {{api}}/users

###
GET  {{api}}/users/5

###
POST {{api}}/users
Content-Type: application/json

{
  "email": "yohan@mail.com",
  "password": "2394092343",
  "role": "customer"
}

###
PATCH {{api}}/users/2
Content-Type: application/json

{
  "email": "testcambio@mail.com"
}

###
DELETE {{api}}/users/3

###
GET {{api}}/products

###
GET {{api}}/customers

###
POST {{api}}/customers
Content-Type: application/json

{
  "name": "Valentina",
  "lastName": "Gonzalez",
  "phone": "04129613339",
  "user": {
    "email": "vale@mail.com",
    "password": "aoeustnha"
  }
}

###

DELETE {{api}}/customers/2