@api = http://localhost:3000/api/v1/products

GET {{api}}

###
GET {{api}}/id

###
POST {{api}}
Content-Type: application/json

{
  "name": "producto 13",
  "price": 20,
  "description": "Esta es una camisa 100% nueva",
  "image": "https://image.com/200/400",
  "categoryId": 3
}

###
PATCH {{api}}/7
Content-Type: application/json

{
  "price": 60
}