version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PORT=3306
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=yohan@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
