@api = {{$dotenv API}}/categories

GET {{api}}

###
GET {{api}}/3

###
POST {{api}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTcwNjAxMTY2NX0.LW0XOTpFhAF0EVj0LsFaAZheyyM25umyB38H6cqOq7w

{
  "name": "Category 3",
  "image": "https://image.com/300/500"
}

###
DELETE {{api}}/3