@api = {{$dotenv API}}/customers

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
  "name": "Yohan",
  "lastName": "Angulo",
  "phone": "04129613339",
  "user": {
    "email": "yohanangulo@mail.com",
    "password": "26678741"
  }
}

###
DELETE {{api}}