@api = {{$dotenv API}}/customers

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
  "name": "Valentina",
  "lastName": "Gonzalez",
  "phone": "04129613339",
  "user": {
    "email": "valentin@mail.com",
    "password": "aoeustnha"
  }
}

###
DELETE {{api}}