@api = {{$dotenv API}}/orders

###
GET {{api}}/1

###
POST {{api}} 
Content-Type: application/json

{
  "customerId": 6
}

###
POST {{api}}/add-item 
Content-Type: application/json

{
  "orderId": 2,
  "productId": 2,
  "amount": 10
}