@api = {{$dotenv API}}/products

GET {{api}}

###
GET {{api}}/id

###
POST {{api}}
Content-Type: application/json

{
  "name": "franela",
  "price": 20,
  "description": "Esta es una camisa 100% nueva",
  "image": "https://image.com/200/400",
  "categoryId": 1
}

###
PATCH {{api}}/7
Content-Type: application/json

{
  "price": 60
}