@api = {{$dotenv API}}/users


GET {{api}}

###
GET  {{api}}/5

###
POST {{api}}
Content-Type: application/json

{
  "email": "anguloyohan98@gmail.com",
  "password": "holamundo",
  "role": "customer"
}

###
PATCH {{api}}/9
Content-Type: application/json

{
  "role": "admin"
}

###
DELETE {{api}}/3


