@api = {{$dotenv API}}/users


GET {{api}}

###
GET  {{api}}/5

###
POST {{api}}
Content-Type: application/json

{
  "email": "anguloyohan98@gmail.com",
  "password": "holamundo",
  "role": "customer"
}

###
PATCH {{api}}/2
Content-Type: application/json

{
  "email": "testcambio@mail.com"
}

###
DELETE {{api}}/3


