@API = http://localhost:3001/api/v1
###
GET {{API}}/products

###
GET {{API}}/products/aoeu

###

POST {{API}}/products
Content-Type: application/json

{
  "name": 23,
  "price": "eou",
  "image": "http://localhost:3001/ image"
}

###

PATCH  {{API}}/products/9f152a06-0754-4425-ae85-a452a835baea
Content-Type: application/json

{
  "name": "new product"
}

###

DELETE {{API}}/products/2bfd327f-4764-4d81-9ec0-3f169526034b