@api = {{$dotenv APP_URL}}/message

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
  "user": "65c8d9ce737f44c606695fb8",
  "message": "si de Yohan para Maria",
  "chat": "65c8d9f2737f44c606695fbc"
}

###
PATCH {{api}}/65c760c683f0c6a5ce043c75
Content-Type: application/json

{
  "message": "mensaje actualizado"
}

###
DELETE {{api}}/64ee999b4aed60b3cd6aa2cb