@api = {{$dotenv APP_URL}}/message

GET {{api}}?chat=65c8df8b649c48432b99bb28

###
GET {{api}}?user=Yohan

###
POST {{api}}
Content-Type: multipart/form-data

{
  "user": "65c8d9ce737f44c606695fb8",
  "message": "Yohan para Maria",
  "chat": "65c8df8b649c48432b99bb28",
  "file": ""
}

###
PATCH {{api}}/65c760c683f0c6a5ce043c75
Content-Type: application/json

{
  "message": "mensaje actualizado"
}

###
DELETE {{api}}/64ee999b4aed60b3cd6aa2cb